version: '3.9'
services:
  db:
    image: mariadb:10.6.4-focal
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD= "{{ MYSQL_ROOT_PW }}"
      - MYSQL_DATABASE= "{{ MYSQL_DB_NAME }}"
      - MYSQL_USER= "{{ MYSQL_USER }}"
      - MYSQL_PASSWORD= "{{ MYSQL_PW }}"

  wordpress:
    image: wordpress:latest
    volumes:
      - wp_data:/var/www/html
    ports:
      - 80:80
    depends_on: 
      - db
    restart: always
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER= "{{ MYSQL_USER }}"
      - WORDPRESS_DB_PASSWORD= "{{ MYSQL_PW }}"
      - WORDPRESS_DB_NAME= "{{ MYSQL_DB_NAME }}"

volumes:
  db_data:
  wp_data:
